# This is a basic workflow that is manually triggered

name: Create Tag Releases

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        description: 'Tag to be created along with release'
        # Input has to be provided for the workflow to run
        required: true
      git_ref: 
        description: 'A git reference to create tag from. Can be either commit hash, or branch name.'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  createRelease:
      name: createRelease
      runs-on: ubuntu-latest
      strategy:
        matrix: #This matrix allows multiple parallel jobs to create tags in the various repos at the same time
          repo: [3scale/porta, 3scale/apisonator, 3scale/APIcast, 3scale/zync, 3scale/apicast-operator, 3scale/3scale-operator]
      steps:
        - name: Create Release for ${{ matrix.repo }}
          uses: aurelien-baudet/workflow-dispatch@v2.1.1
          with:
            ref: refs/heads/master # <-- this action is triggered in a repo with a 'main' branch, but targets a repo that uses 'master', this needs to be added as a workaround to stop workflow dispatch from triggering the action in a main branch that does not exist.
            repo: ${{ matrix.repo }}
            token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
            workflow: tagRelease.yml
            inputs: '{ "tag": "${{ inputs.tag }}", "git_ref": "${{ inputs.git_ref }}"}'
            wait-for-completion: true
            display-workflow-run-url: true
        - name: Create Release for 3scale/3scale_toolbox
          uses: aurelien-baudet/workflow-dispatch@v2.1.1
          with:
            repo: 3scale/3scale_toolbox
            token: ${{secrets.ACCESS_TOKEN_GITHUB}}
            workflow: tagRelease.yml
            inputs: '{ "tag": "${{ inputs.tag }}", "git_ref": "${{ inputs.git_ref }}"}'
            wait-for-completion: true
            display-workflow-run-url: true
        - name: Create Release for 3scale/searchd
          uses: aurelien-baudet/workflow-dispatch@v2.1.1
          with:
            repo: 3scale/searchd
            token: ${{secrets.ACCESS_TOKEN_GITHUB}}
            workflow: tagRelease.yml
            inputs: '{ "tag": "${{ inputs.tag }}", "git_ref": "${{ inputs.git_ref }}"}'
            wait-for-completion: true
            display-workflow-run-url: true
            
